Repository mattermost/mattermost-plugin-agenda, pull requests merged in 2020-03, with the labels that each got.

#14 Update Circle CI
  .circleci/config.yml
Labels: 2: Dev Review

#16 Add Badges
  README.md
Labels: 3: Reviews Complete

#2 MM-21154 - Agenda Plugin Review
  .gitignore
  Makefile
  README.md
  assets/channelHeaderDropdown.png
  assets/settingsDialog.png
  go.mod
  go.sum
  package-lock.json
  plugin.json
  public/hello.html
  server/command.go
  server/manifest.go
  server/meeting.go
  server/plugin.go
  server/plugin_test.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.js
  webapp/src/components/meeting_settings/index.js
  webapp/src/components/meeting_settings/meeting_settings.jsx
  webapp/src/index.js
  webapp/src/manifest.js
  webapp/src/selectors.js
  webapp/webpack.config.js
Labels: 3: Reviews Complete, QA Review Done

#19 GH-18 - Improve hashtag help text
  webapp/src/components/meeting_settings/meeting_settings.jsx
Labels: 3: Reviews Complete, QA Review Done
